# Generated by Django 4.2.1 on 2023-06-03 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0003_customeuser_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomeUser',
            new_name='CustomUser',
        ),
    ]
