# Generated by Django 4.2.1 on 2023-06-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_priceperkg_alter_profile_package_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceperkg',
            name='price',
            field=models.FloatField(),
        ),
    ]
