# Generated by Django 4.2.1 on 2023-08-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_alter_priceperkg_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
