# Generated by Django 4.2.1 on 2023-08-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_profile_country_name_profile_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country_name',
        ),
    ]
