# Generated by Django 4.2.1 on 2023-08-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_customuser_destinationcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='destinationCountry',
            field=models.TextField(default=''),
        ),
    ]
