# Generated by Django 4.2.1 on 2023-08-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_warehousepackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_uploadpackage',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='notification_uploadpackage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='warehousepackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='warehousepackage',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Notification_UpdateConsolidation',
        ),
        migrations.DeleteModel(
            name='Notification_UploadPackage',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='WarehousePackage',
        ),
    ]
