# Generated by Django 4.2.1 on 2023-09-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_remove_notification_uploadpackage_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
