# Generated by Django 4.2.1 on 2023-08-29 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InProgressPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_required', models.BooleanField(default=False)),
                ('selected_action', models.CharField(choices=[('forward', 'Forward'), ('repackage', 'Repackage'), ('consolidate', 'Consolidate'), ('no_decision', 'No Decision')], default='no_decision', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_action', models.CharField(choices=[('forward', 'Forward'), ('repackage', 'Repackage'), ('consolidate', 'Consolidate'), ('no_decision', 'No Decision')], default='no_decision', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('destinationCountry', models.TextField(default='')),
                ('package_image', models.ImageField(blank=True, null=True, upload_to='package_images')),
                ('package_dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_name', models.TextField(blank=True, max_length=200, null=True)),
                ('package_price', models.IntegerField(blank=True, null=True)),
                ('package_description', models.TextField(blank=True, null=True)),
                ('forward_consolidation', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarehousePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_required', models.BooleanField(default=False)),
                ('selected_action', models.CharField(choices=[('forward', 'Forward'), ('repackage', 'Repackage'), ('consolidate', 'Consolidate'), ('no_decision', 'No Decision')], default='no_decision', max_length=20)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_package', to='package.package')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyToShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_required', models.BooleanField(default=False)),
                ('selected_action', models.CharField(choices=[('forward', 'Forward'), ('repackage', 'Repackage'), ('consolidate', 'Consolidate'), ('no_decision', 'No Decision')], default='no_decision', max_length=20)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_to_ship', to='package.package')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.profile')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='in_progress_packages',
            field=models.ManyToManyField(related_name='in_progress_packages', through='package.InProgressPackage', to='package.profile'),
        ),
        migrations.AddField(
            model_name='package',
            name='ready_to_ship_packages',
            field=models.ManyToManyField(related_name='ready_to_ship_packages', through='package.ReadyToShip', to='package.profile'),
        ),
        migrations.AddField(
            model_name='package',
            name='warehouse_packages',
            field=models.ManyToManyField(related_name='warehouse_packages', through='package.WarehousePackage', to='package.profile'),
        ),
        migrations.AddField(
            model_name='inprogresspackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_progress', to='package.package'),
        ),
        migrations.AddField(
            model_name='inprogresspackage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.profile'),
        ),
    ]
