# Generated by Django 4.2.1 on 2023-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_profile_package_description_profile_package_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePerKg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='package_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='package_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
