# Generated by Django 4.2.1 on 2023-08-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_remove_profile_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='destinationCountry',
            field=models.TextField(default=''),
        ),
    ]
