# Generated by Django 4.2.1 on 2023-08-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0016_profile_destinationcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forward_consolidation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='forward_consolidation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notification_UploadPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interface.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification_UpdateConsolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interface.profile')),
            ],
        ),
    ]
