# Generated by Django 4.2.1 on 2023-08-14 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0017_customuser_forward_consolidation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_uploadpackage',
            name='message',
        ),
        migrations.AddField(
            model_name='notification_updateconsolidation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification_uploadpackage',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
