# Generated by Django 4.2.1 on 2023-08-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0018_remove_notification_uploadpackage_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehousePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_required', models.BooleanField(default=False)),
                ('selected_action', models.CharField(choices=[('forward', 'Forward'), ('repackage', 'Repackage'), ('consolidate', 'Consolidate'), ('no_decision', 'No Decision')], default='no_decision', max_length=20)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_packages', to='interface.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.profile')),
            ],
        ),
    ]
